### ISSUE TITLE
Compound (multi-block / multi-spectra) data sets not supported

### ISSUE THREAD

**Issue by rguliev** [bryanhanson/readJDX#2]
Hi, 
tried to import jdx file (attached) containing time series. The following error message appears:
```
Error in readJDX("Ag#Al2O3_1.jdx") : 
  Compound (multi-block / multi-spectra) data sets not supported
```
Why is it not supported?

[Ag#Al2O3_1.txt](https://github.com/bryanhanson/readJDX/files/569653/Ag.Al2O3_1.txt)

**Comment by bryanhanson** [comment]
It’s not supported primarily because it has taken so long to get a non-compound file import working.  I have designed the overall flow to make it fairly easy to add compound file support however.  Given what I have to do in the next few months I don’t think I can give any time to it until probably next summer.  I’m going to leave this issue open and mark it as a feature request however.  Support should be added, it’s just a matter of time.  Maybe someone will fork the project and add it.

Bryan

**Comment by bryanhanson** [comment]
Surprise!  https://github.com/bryanhanson/readJDX/commit/83e0385e56dbd98acb21f55ec019cb6b83020b30 now has a function `splitMultiblockDX()` that will split multiblock files into separate files.  After that, one can use the usual `readJDX` functions to process the individual files. Will be on CRAN shortly.
